### ISSUE TITLE
ResourceNotFound: Cannot find a resource matching chef_ingredient[manage] (did you define it first?)

### ISSUE THREAD

**Issue by brylor** [mengesb/tf_chef_server#67]
Hi, I'm trying to get a chef server installed onto AWS with terraform and the tf_chef_server module. Unfortunately I get an error. 

Note I also had to remove the extra slashes in the following to proceed or I got this error:
```
module.module_name_here.aws_instance.chef-server (remote-exec):           cense": true,     "addons": [manage,push-jobs-server,reporti
module.module_name_here.aws_instance.chef-server (remote-exec):                      (right here) ------^
```

main.tf

from:

```
data "template_file" "attributes-json" {
  template = "${file("${path.module}/files/attributes-json.tpl")}"
  vars {
    addons  = "${join(",", formatlist("\\"%s\\"", split(",", var.chef_addons)))}"
```

to:

```
data "template_file" "attributes-json" {
  template = "${file("${path.module}/files/attributes-json.tpl")}"
  vars {
    addons  = "\"${join(",", formatlist("%s", split(",", var.chef_addons)))}\""
```

I also had to set in chef-cookbooks.sh:
```
curl -sL https://supermarket.chef.io/cookbooks/cron/versions/1.7.0/download | sudo tar xzC /var/chef/cookbooks
```
Because the system recipe has cron 1.7.0 as a dependency

Unfortunately I still get this, is it related to the license accepted? I have chef_license = "true" in the module declaration. Please help. Thanks:
```
ubuntu@ip-10-0-1-130:~$ sudo chef-solo -j .chef/dna.json -o 'recipe[system::default],recipe[chef-server::default],recipe[chef-server::addons]'
sudo: unable to resolve host ip-10-0-1-130
[2018-03-13T23:01:18+00:00] WARN: *****************************************
[2018-03-13T23:01:18+00:00] WARN: Did not find config file: /etc/chef/solo.rb, using command line options.
[2018-03-13T23:01:18+00:00] WARN: *****************************************
[2018-03-13T23:01:18+00:00] WARN: *****************************************
[2018-03-13T23:01:18+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2018-03-13T23:01:18+00:00] WARN: *****************************************
Starting Chef Client, version 12.16.42
[2018-03-13T23:01:19+00:00] WARN: Run List override has been provided.
[2018-03-13T23:01:19+00:00] WARN: Original Run List: []
[2018-03-13T23:01:19+00:00] WARN: Overridden Run List: [recipe[system::default], recipe[chef-server::default], recipe[chef-server::addons]]
resolving cookbooks for run list: ["system::default", "chef-server::default", "chef-server::addons"]
Synchronizing Cookbooks:
  - cron (1.7.0)
  - hostsfile (3.0.1)
  - chef-server (5.5.1)
  - apt (6.1.4)
  - system (0.11.3)
  - chef-ingredient (2.3.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 20 resources

Running handlers:
[2018-03-13T23:01:19+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-03-13T23:01:19+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2018-03-13T23:01:19+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-03-13T23:01:19+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-03-13T23:01:19+00:00] ERROR: resource chef_ingredient[manage,push-jobs-server,reporting] is configured to notify resource chef_ingredient[manage,push-jobs-server,reporting] with action reconfigure, but chef_ingredient[manage,push-jobs-server,reporting] cannot be found in the resource collection. chef_ingredient[manage,push-jobs-server,reporting] is defined in /etc/chef/local-mode-cache/cache/cookbooks/chef-server/recipes/addons.rb:20:in `block in from_file'

[2018-03-13T23:01:19+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ubuntu@ip-10-0-1-130:~$ sudo cat /etc/chef/local-mode-cache/cache/chef-stacktrace.out
sudo: unable to resolve host ip-10-0-1-130
Generated at 2018-03-13 23:01:19 +0000
Chef::Exceptions::ResourceNotFound: resource chef_ingredient[manage,push-jobs-server,reporting] is configured to notify resource chef_ingredient[manage,push-jobs-server,reporting] with action reconfigure, but chef_ingredient[manage,push-jobs-server,reporting] cannot be found in the resource collection. chef_ingredient[manage,push-jobs-server,reporting] is defined in /etc/chef/local-mode-cache/cache/cookbooks/chef-server/recipes/addons.rb:20:in `block in from_file'

/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:56:in `lookup'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:160:in `block in find_resource_by_string'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:159:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:159:in `find_resource_by_string'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:91:in `block in find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:86:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:86:in `find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection.rb:130:in `find_recursive'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection.rb:116:in `find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource/resource_notification.rb:59:in `fix_resource_reference'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource/resource_notification.rb:48:in `resolve_resource_reference'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1305:in `block in resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1304:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1304:in `resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:92:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:91:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/solo.rb:226:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:54:in `load'
/usr/bin/chef-solo:54:in `<main>'

>>>> Caused by Chef::Exceptions::ResourceNotFound: Cannot find a resource matching chef_ingredient[manage] (did you define it first?)
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:56:in `lookup'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:160:in `block in find_resource_by_string'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:159:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:159:in `find_resource_by_string'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:91:in `block in find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:86:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection/resource_set.rb:86:in `find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection.rb:130:in `find_recursive'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource_collection.rb:116:in `find'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource/resource_notification.rb:59:in `fix_resource_reference'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource/resource_notification.rb:48:in `resolve_resource_reference'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1305:in `block in resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1304:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/resource.rb:1304:in `resolve_notification_references'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:92:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/runner.rb:91:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/solo.rb:226:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:54:in `load'
```

**Comment by mengesb** [comment]
Your change resulted in a bad set for the add-ons

`chef_ingredient[manage,push-jobs-server,reporting]`

The split you did there doesn't work.

Indeed syntax should have removed the quad quotes for double quotes. I'll
look into updating versions and give it a test soon.

**Comment by mengesb** [comment]
Have you taken another stab at this recently?
